# Covering a range of basic to advanced functionalities Of Numpy:

In [5]:
# Importing Numpy
import numpy as np

# Basic Operations

In [6]:
# Creating an array from a list:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# Creating a 2D array:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)

[[1 2]
 [3 4]]


In [9]:
# Creating an array of zeros:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Creating an array of ones:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Creating an array with a constant value:
const_array = np.full((3, 3), 7)
print(const_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
# Creating an array with a range of values:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [13]:
# Creating an array of evenly spaced values:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
# Creating an identity matrix:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# Creating a random array:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.2800036  0.24768729 0.13215792]
 [0.38175888 0.43954399 0.66781232]
 [0.26575169 0.15435785 0.75512528]]


# Array Manipulation

In [16]:
# Reshaping an array:
reshaped = np.arange(9).reshape(3, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# Flattening an array:
flat_arr = reshaped.flatten()
print(flat_arr)

[0 1 2 3 4 5 6 7 8]


In [18]:
# Transposing an array:
transposed = reshaped.T
print(transposed)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [19]:
# Concatenating arrays:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated = np.concatenate((a, b))
print(concatenated)

[1 2 3 4 5 6]


In [20]:
# Stacking arrays vertically:
stacked_v = np.vstack((a, b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [21]:
# Stacking arrays horizontally:
stacked_h = np.hstack((a, b))
print(stacked_h)

[1 2 3 4 5 6]


In [22]:
# Splitting an array:
split_arr = np.split(np.arange(10), 2)
print(split_arr)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [23]:
# Repeating elements of an array:
repeated = np.repeat([1, 2, 3], 3)
print(repeated)

[1 1 1 2 2 2 3 3 3]


In [24]:
# Tiling an array:
tiled = np.tile([1, 2], (3, 2))
print(tiled)

[[1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]]


In [25]:
# Changing data type of an array:
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


In [54]:
# Adding Two Arrays
added_arr = arr + np.array([5, 4, 3, 2, 1])
print(added_arr)

[5 4 6 6 6]


In [55]:
# Subtracting Two Arrays
subtracted_arr = arr - np.array([1, 1, 1, 1, 1])
print(subtracted_arr)

[-1 -1  2  3  4]


In [56]:
#Multiplying Two Arrays
multiplied_arr = arr * np.array([2, 2, 2, 2, 2])
print(multiplied_arr)

[ 0  0  6  8 10]


# Indexing and Slicing

In [26]:
# Accessing elements:
element = arr[2]  # 3rd element
print(element)

3


In [27]:
# Slicing arrays:
sliced = arr[1:4]  # Elements from index 1 to 3
print(sliced)

[2 3 4]


In [28]:
# Advanced indexing:
selected = arr[[0, 2, 4]]  # Elements at positions 0, 2, and 4
print(selected)

[1 3 5]


In [29]:
# Boolean indexing:
bool_idx = arr[arr > 2]
print(bool_idx)

[3 4 5]


In [30]:
# Indexing in 2D arrays:
element_2d = arr_2d[1, 1]  # Element at 2nd row, 2nd column
print(element_2d)

4


# Mathematical Operations

In [33]:
# Element-wise addition:
sum_arr = arr + 1
print(sum_arr)

[2 3 4 5 6]


In [34]:
# Element-wise multiplication:
product_arr = arr * 2
print(product_arr)

[ 2  4  6  8 10]


In [35]:
# Matrix multiplication:
mat_mult = np.dot(arr_2d, arr_2d)
print(mat_mult)

[[ 7 10]
 [15 22]]


In [36]:
# Finding the sum of all elements:
total_sum = arr.sum()
print(total_sum)

15


In [37]:
# Finding the mean:
mean_val = arr.mean()
print(mean_val)

3.0


In [38]:
# Finding the standard deviation:
std_val = arr.std()
print(std_val)

1.4142135623730951


In [39]:
# Finding the maximum and minimum values:
max_val = arr.max()
min_val = arr.min()
print(max_val)
print(min_val)

5
1


In [40]:
# Cumulative sum of elements:
cum_sum = arr.cumsum()
print(cum_sum)

[ 1  3  6 10 15]


In [41]:
# Finding unique elements:
unique_elements = np.unique([1, 2, 2, 3, 4, 4, 5])
print(unique_elements)

[1 2 3 4 5]


# Masking and Filtering

In [42]:
# Masking with conditions:
mask = arr > 3
filtered = arr[mask]
print(filtered)

[4 5]


In [48]:
# Replacing values conditionally:
arr[arr < 3] = 0
print(arr)

[0 0 3 4 5]


In [49]:
# Using where for conditional replacement:
modified_arr = np.where(arr > 3, arr, 0)
print(modified_arr)

[0 0 0 4 5]


# Advanced Functions

In [50]:
# Broadcasting:
broadcast_result = arr + np.array([1])
print(broadcast_result)

[1 1 4 5 6]


In [51]:
# Sorting an array:
sorted_arr = np.sort(arr)
print(sorted_arr)

[0 0 3 4 5]


In [53]:
# Applying functions element-wise with vectorize:
def square(x):
    return x ** 2

vectorized_square = np.vectorize(square)
result = vectorized_square(arr)
result

array([ 0,  0,  9, 16, 25])